#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "$2" ]; then
            echo "Updating init script links and actions."
            deb-systemd-helper disable openvpn.service >/dev/null || true
            deb-systemd-invoke stop openvpn.service >/dev/null || true

            # Restart rsyslog to load the provided configuration if rsyslog is
            # installed and enabled since we're not dependent on it. Only needs
            # to be done when the plugin is installed.
            if deb-systemd-helper debian-installed rsyslog.service; then
                if deb-systemd-helper is-enabled rsyslog.service; then
                    deb-systemd-invoke restart rsyslog.service >/dev/null || true
                fi
            fi
        fi

        # Activate package triggers.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.openvpn"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.openvpn" "${2}"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
