#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "$2" ]; then
            echo "Updating init script links and actions."
            deb-systemd-helper disable openvpn.service >/dev/null || true
            deb-systemd-invoke stop openvpn.service >/dev/null || true

            # Restart rsyslog to load the provided configuration if rsyslog is
            # installed and enabled since we're not dependent on it. Only needs
            # to be done when the plugin is installed.
            if deb-systemd-helper debian-installed rsyslog.service; then
                if deb-systemd-helper is-enabled rsyslog.service; then
                    deb-systemd-invoke restart rsyslog.service >/dev/null || true
                fi
            fi
        fi

        SERVICE_XPATH_NAME="openvpn"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_node "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_key "${SERVICE_XPATH}" "enable" "0"

            omv_config_add_key "${SERVICE_XPATH}" "port" "1194"
            omv_config_add_key "${SERVICE_XPATH}" "protocol" "udp"
            omv_config_add_key "${SERVICE_XPATH}" "compression" "1"
            omv_config_add_key "${SERVICE_XPATH}" "pam_authentication" "0"
            omv_config_add_key "${SERVICE_XPATH}" "extra_options" ""
            omv_config_add_key "${SERVICE_XPATH}" "loglevel" "2"

            omv_config_add_key "${SERVICE_XPATH}" "vpn_network" "10.8.0.0"
            omv_config_add_key "${SERVICE_XPATH}" "vpn_mask" "255.255.255.0"
            omv_config_add_key "${SERVICE_XPATH}" "default_gateway" "1"
            omv_config_add_key "${SERVICE_XPATH}" "client_to_client" "0"

            omv_config_add_key "${SERVICE_XPATH}" "dns" ""
            omv_config_add_key "${SERVICE_XPATH}" "dns_domains" ""
            omv_config_add_key "${SERVICE_XPATH}" "wins" ""

            omv_config_add_key "${SERVICE_XPATH}" "public_address" ""

            omv_config_add_node "${SERVICE_XPATH}" "clients" ""
        fi

        addgroup --quiet \
                 --system \
                 openvpn

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
